language: java
jdk:
- oraclejdk8
sudo: false
env:
  global:
  - secure: OMgBCaGjF+aUQ/ql1FYEffvDXW8KKiod85cXIIh5K3NuSU7l1acWd3skKatl0QdlyUn+abJeiO3IgXAF1DsY36fpsJvp8KanjBBCHyp1aXukC1aLP22B+k3SSM2BH8OEfvnF5brhX36MBPrZ3WmHQ7hFgVqO1iIZDmRu90SYxLWNbeg+RxIOHzDTXeA3uRREOPM8lNEzZRDbbBkPhF/nhQIerKvNzYwr8j5gnKu0TxiAU7i+6F89at4+CUsVSRT6NuhKbwoEPQjnQ3ZWQQNONFCVEXk/k7Q4ouYapApJU1rMu7ioUOwok+D/T+6Pe3EknE8qW5oanUVAm1+BhUyy7kO5LnIPqOG9OCEw4nAQ6QF3vsHkhjykhmMX5nBaHAc65CouZy8nbVf66qro9msGO0s0Kgv5ozDs5YLmg176uw9S4iuSEhNsllHLZvtaIXHBhmnAz4UYYL11nUom9EEn5t7fuq5cxZ1crROVNiuCOjSHJLwemfFKqzx3h3AsqHxyz2QCtDF8jE76nymQ12sR3QK6b9WzT1xsPGGNQCVtRMtPZcTWnQrpK0LjdC9s6Cn+vGkE47lN0pvxkVJ9/hJCcM25FvYPICUp3njoOpXEoAfq0FVPmn6xkQmJ1j9gjtR8Z7pKZ2Z/76je5uOWJnBBw2ZhvmtPhnVzLbjHXKu7Q98=
script:
  - ./build.sh
after_success:
  - ./upload.sh
